# Generated by Django 5.1.1 on 2024-10-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ic_cikgu',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ic_pelajar',
        ),
        migrations.AlterField(
            model_name='report',
            name='kelas',
            field=models.CharField(blank=True, choices=[('-', '-'), ('ANGGERIK', 'ANGGERIK'), ('CEMPAKA', 'CEMPAKA'), ('DAHLIA', 'DAHLIA'), ('MAWAR', 'MAWAR'), ('SEROJA', 'SEROJA'), ('TERATAI', 'TERATAI'), ('UM', 'UM'), ('UKM', 'UKM'), ('USM', 'USM'), ('LILY', 'LILY')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='pangkat',
            field=models.CharField(blank=True, choices=[('Pengerusi', 'Pengerusi'), ('Naib Pengerusi', 'Naib Pengerusi'), ('Pegawai Ehwal Ekonomi', 'Pegawai Ehwal Ekonomi'), ('Penolong Pegawai Ehwal Ekonomi', 'Penolong Pegawai Ehwal Ekonomi'), ('Juruaudit', 'Juruaudit'), ('Penolong Juruaudit', 'Penolong Juruaudit'), ('Guru Biasa', 'Guru Biasa'), ('Lain-lain', 'Lain-lain')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='tingkatan',
            field=models.CharField(blank=True, choices=[('-', '-'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True),
        ),
    ]
