# Generated by Django 5.1.1 on 2024-09-27 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ic_pelajar',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='IC must be exactly 12 digits')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='kelas',
            field=models.CharField(choices=[('-', '-'), ('ANGGERIK', 'ANGGERIK'), ('CEMPAKA', 'CEMPAKA'), ('DAHLIA', 'DAHLIA'), ('MAWAR', 'MAWAR'), ('SEROJA', 'SEROJA'), ('TERATAI', 'TERATAI'), ('UM', 'UM'), ('UKM', 'UKM'), ('USM', 'USM'), ('LILY', 'LILY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='tingkatan',
            field=models.CharField(choices=[('-', '-'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
    ]
