# Generated by Django 5.1.1 on 2024-09-12 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0002_alter_teacher_pangkat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saham',
            fields=[
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('share_date', models.DateField(auto_now_add=True)),
                ('share_type', models.CharField(choices=[('Initial', 'Initial'), ('Additional', 'Additional')], default='Initial', max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.member')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
