# Generated by Django 5.1 on 2024-09-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_member_ic_pelajar_alter_member_kelas_and_more'),
        ('student', '0002_alter_member_kelas_alter_member_tingkatan'),
    ]

    operations = [
    ]
