# Generated by Django 5.1 on 2024-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('student', '0003_merge_20240927_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='kaum',
            field=models.CharField(choices=[('-', '-'), ('IBAN ATAU SEA DAYAK', 'IBAN ATAU SEA DAYAK'), ('INDONESIA', 'INDONESIA'), ('KADAZAN', 'KADAZAN'), ('KAYAN', 'KAYAN'), ('MELAYU', 'MELAYU'), ('ORANG ASLI', 'ORANG ASLI'), ('SEMAI', 'SEMAI'), ('THAI', 'THAI'), ('LAIN-LAIN', 'LAIN-LAIN')], max_length=50),
        ),
    ]
