# Generated by Django 5.1 on 2024-09-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_merge_20240928_1942'),
        ('student', '0004_alter_member_kaum'),
    ]

    operations = [
    ]
